### ISSUE TITLE
Border Radius Properties Not Show Up 

### ISSUE THREAD

**Issue by geekfast** [EightShapes/specs-plugin-feedback#36] opened 2023-02-16 10:58 UTC
**Layout and Spacing**
missing Border radius properties

**Comment by nathanacurtis** [comment] 2023-02-16 12:14
@geekfast Could you provide details on your case, such as how your component is built and plugin outputs, so that I can diagnose where the issue is. If it's the same issue as #34, you can close this issue.

**Comment by nathanacurtis** [comment] 2023-02-16 14:30
@geekfast After fixing #34, I'm confident this resolves your problem (a `border-radius` attribute shown on a frame layer or top-layer of an instance).

**Comment by nathanacurtis** [comment] 2023-02-21 13:13
Closing as resolved.

**Closed by nathanacurtis** 2023-02-21 13:13 UTC
Labels: defect, Attribute
