### ISSUE TITLE
Anatomy not honoring component

### ISSUE THREAD

**Issue by inetwebguy** [EightShapes/specs-plugin-feedback#48] opened 2023-02-24 23:59 UTC
### Steps to reproduce

1.  Create a primary container and apply an Auto Layout with a fixed width (in my case it's 720px)
2. Add content to the auto layout
3. Run Specs plugin

### Expected behavior

Anatomy would reflect visual (width) of the component

### Screenshot

<img width="947" alt="Screenshot 2023-02-24 at 6 09 46 PM" src="https://user-images.githubusercontent.com/16294046/221319826-e216a4b3-d9d1-442c-8969-212242395433.png">

### Other

Changing the width of the primary container's auto layout from "Fixed" to "Hug" displays the expected behavior.

**Comment by nathanacurtis** [comment] 2023-02-25 12:37
Thanks @inetwebguy for your submission. This is a duplicate of known issue #40. I'm going to copy your description as a comment to that issue and close this issue. I've been inspecting the root cause of this, and it seems like a Figma behavior when cloning a component into a frame, and the fix – other than brute force checking for this resizing swap and changing it back – remains elusive.

**Closed by nathanacurtis** 2023-02-25 12:37 UTC
Labels: defect

**Comment by nathanacurtis** [comment] 2023-02-27 14:07
Fixed and published as new plugin version.
